#!/usr/bin/env bash
set -euo pipefail

case "${1:-}" in
    purge)
        rm -f /etc/nginx/veeapp.htpasswd
        rm -f /etc/nginx/sites-enabled/veeapp

        rm -rf /etc/default/veeapp

        systemctl daemon-reload

        if systemctl is-active --quiet nginx; then
            systemctl reload nginx || true
        fi

        if systemctl is-active --quiet fail2ban; then
            systemctl restart fail2ban || true
        fi
        ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
esac

exit 0
