server:
  forward-headers-strategy: framework
  address: 127.0.0.1
  port: 9099

spring:
  application:
    name: veeapp-backend
  threads:
    virtual:
      enabled: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration

app:
  xray:
    config-path: /usr/local/etc/xray/config.json
  server:
    init-conf-path: /etc/default/veeapp/init.conf
  command:
    timeout-ms: 60000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
